name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.2.0
  intl: ^0.19.0
  image_picker: ^1.1.2
  uuid: ^3.0.7
  pdf: ^3.11.1
  barcode_widget: ^2.0.4
  printing: ^5.13.3
  responsive_sizer: ^3.3.1
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  shared_preferences: ^2.0.13

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo Atma GYM.png
    - lib/assets/bca_mobile.png
    - lib/assets/bni.png
    - lib/assets/gopay.png
    - lib/assets/Shopeepay.png


